name: deploy on ec2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@main
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/html/DAFrontend
          pwd
          sudo git pull origin main
          sudo rm -rf build
          sudo yarn 
          sudo yarn run build
          sudo pm2 ls
          sudo pm2 restart all
