name: deploy on ec2
on:
  push:
    branches: 
       - main

       
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/html/DAFrontend
          git config --global --add safe.directory /var/www/html/DAFrontend
          ls -la
          sudo git pull
          sudo yarn
          sudo yarn run build
          sudo pm2 ls
          sudo pm2 restart all
